name: Release

on:
  push:
    branches:
      - master
      - feature/gh-actions
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-2019

    env:
      DXSDK_DIR: '${{ github.workspace }}/DXSDK/'

    steps:
      - uses: actions/checkout@v3

      # Used by release.bat
      - name: Install zip
        run: |
          curl -sL https://downloads.sourceforge.net/gnuwin32/zip-3.0-bin.zip -o zip.zip
          7z x zip.zip * -ozip-30
          echo "${{ github.workspace }}/zip-30/bin" | `
          Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86

      - name: Install DirectX SDK
        run: |
          curl -sL https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -o DXSDK_Jun10.exe
          7z x DXSDK_Jun10.exe DXSDK/Include -otmp
          7z x DXSDK_Jun10.exe DXSDK/Lib -otmp
          mv tmp/DXSDK DXSDK

      - name: Install Windows SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        with:
          sdk-version: 16299

      - name: Install Wix Toolkit
        run: |
          Invoke-WebRequest -UseBasicParsing -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe -OutFile wix311.exe
          & ".\wix311.exe" "/q"

      - name: Build 32-bit
        run: |
          msbuild PinballY.sln -p:Configuration=Release -p:Platform=x86

      - name: Build 64-bit
        run: |
          msbuild PinballY.sln -p:Configuration=Release -p:Platform=x64 -t:Clean

      - name: Create release
        run: ./release.bat

      - name: List release
        run: dir Builds

